import type {
    StripeDemoCatalog,
} from '../types/stripe-demo-catalog';

/**
 * AUTO-GENERATED FILE.
 *
 * Generated by:
 *
 * npm run stripe:create-test-catalog
 *
 * Do not edit the Stripe IDs manually.
 */
export const stripeDemoCatalog:
    StripeDemoCatalog = {
    "tug-and-fetch-rope-ball": {
        "stripeProductId": "prod_Uxb1rqfcScZfNu",
        "variantPriceIds": {},
        "stripeDefaultPriceId": "price_1TxfpPCpMg02SFmCDnVoWoqK"
    },
    "whisker-feather-wand": {
        "stripeProductId": "prod_Uxb1h7poe5eI1J",
        "variantPriceIds": {},
        "stripeDefaultPriceId": "price_1TxfpQCpMg02SFmCNj5TlyFY"
    },
    "adventure-fit-harness": {
        "stripeProductId": "prod_Uxb1ikgTVbPJq1",
        "variantPriceIds": {
            "small": "price_1TxfpRCpMg02SFmCX5KgWdr3",
            "medium": "price_1TxfpRCpMg02SFmCeuAVETJ6",
            "large": "price_1TxfpRCpMg02SFmC4a2VOsGj"
        }
    },
    "trail-loop-leash": {
        "stripeProductId": "prod_Uxb1AC0yuZ8Url",
        "variantPriceIds": {},
        "stripeDefaultPriceId": "price_1TxfpSCpMg02SFmCZbA0SthX"
    },
    "duo-ceramic-bowl-set": {
        "stripeProductId": "prod_Uxb1riETMoh8p3",
        "variantPriceIds": {},
        "stripeDefaultPriceId": "price_1TxfpTCpMg02SFmCaVKE0knn"
    },
    "slow-moment-feeding-bowl": {
        "stripeProductId": "prod_Uxb10MGPmlMloM",
        "variantPriceIds": {},
        "stripeDefaultPriceId": "price_1TxfpTCpMg02SFmCbBFecGHf"
    },
    "cloud-nest-pet-bed": {
        "stripeProductId": "prod_Uxb1F5X0bCfWAD",
        "variantPriceIds": {
            "small": "price_1TxfpUCpMg02SFmCqLJMEL5t",
            "medium": "price_1TxfpVCpMg02SFmCZz5rhJzY",
            "large": "price_1TxfpVCpMg02SFmCKZSKjrij"
        }
    },
    "cozy-basket-lounger": {
        "stripeProductId": "prod_Uxb1951xVQllQI",
        "variantPriceIds": {},
        "stripeDefaultPriceId": "price_1TxfpWCpMg02SFmCbcOzzmny"
    },
    "everyday-slicker-brush": {
        "stripeProductId": "prod_Uxb1wRZPeEkLqh",
        "variantPriceIds": {},
        "stripeDefaultPriceId": "price_1TxfpWCpMg02SFmCMXXXYHiW"
    },
    "paw-rinse-cleaning-cup": {
        "stripeProductId": "prod_Uxb1jv2rqhQOO0",
        "variantPriceIds": {},
        "stripeDefaultPriceId": "price_1TxfpXCpMg02SFmCHQA9mDN6"
    },
    "classic-everyday-collar": {
        "stripeProductId": "prod_Uxb1PvJnFEC6WH",
        "variantPriceIds": {
            "small": "price_1TxfpYCpMg02SFmCBl2YspI9",
            "medium": "price_1TxfpYCpMg02SFmCTSk4BibH",
            "large": "price_1TxfpZCpMg02SFmC56SZeBeV"
        }
    },
    "paw-charm-pet-collar": {
        "stripeProductId": "prod_Uxb1Gsqf3VQNPR",
        "variantPriceIds": {},
        "stripeDefaultPriceId": "price_1TxfpZCpMg02SFmCuaRyunq1"
    }
};
